# Generated by Django 3.2.9 on 2022-02-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_auto_20220214_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
